networks:
  springbootapp-network:
    driver: bridge
services:
  backend:
    build: .
    container_name: backend
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - springbootapp-network
    environment:
      - DATABASE_HOST=db # redefines localhost in .env file
  db:
    image: postgres:18
    container_name: db
    restart: always
    shm_size: 128mb # set shared memory limit when using docker compose
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_SCHEMA}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - springbootapp-network
  rabbitmq:
    image: rabbitmq:management-alpine # login/password guest/guest by default here in container and in spring configuration
    container_name: rabbitmq
    restart: always
    configs:
      - source: plugins
        target: /etc/rabbitmq/enabled_plugins # we need to enable stream plugin
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # HTTP management UI
      - "5552:5552" # Streams protocol
    networks:
      - springbootapp-network
configs:
  plugins:
    content: "[rabbitmq_management, rabbitmq_mqtt, rabbitmq_stream, rabbitmq_stomp, rabbitmq_stream_management]."