spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    open-in-view: false
#    show-sql: true # show sql statements
    hibernate:
      ddl-auto: create # Creates the schema and destroys previous data
      properties:
        hibernate.jdbc.time_zone: UTC
        hibernate.default_schema: ${DATABASE_SCHEMA}
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_SCHEMA}?${DATABASE_PROPERTIES}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
#logging:
#  level:
#    org.hibernate.SQL: debug # the same spring.jpa.show-sql=true
#    org.hibernate.orm.jdbc.bind: trace # show values in sql statements